Repository rancher/elemental-docs, pull requests merged in 2024-10, with the labels that each got.

#407 Document CA cert lifecycle
  docs/certificate-authority.md
  sidebars.js
Labels: area/documentation, area/security

#406 Adding documentation for hook stages
  docs/cloud-config-reference.md
  docs/machineregistration-reference.md
Labels: kind/enhancement

#421 Add hooks docs for 1.6 and improve Next version
  docs/cloud-config-reference.md
  versioned_docs/version-1.6/cloud-config-reference.md
Labels: area/documentation
